apiVersion: kbld.k14s.io/v1alpha1
kind: Config
overrides:
- image: capabilities-controller-manager:latest
  newImage: projects.registry.vmware.com/lubron/tkg/management/capabilities-controller-manager:latest
